#!/usr/bin/env python3
"""Bundle data/*.json into site/data.js as window.MR.

Inlined rather than fetched so the site works from file://, GitHub Pages, or
any static host with no server and no CORS story.
"""
import json, pathlib, sys, datetime

ROOT = pathlib.Path(__file__).resolve().parent.parent
DATA, SITE = ROOT / "data", ROOT / "site"

FILES = ["opportunities", "vendors", "costs", "sectors", "gaps"]

def main():
    bundle = {}
    for name in FILES:
        p = DATA / f"{name}.json"
        if not p.exists():
            print(f"missing {p}", file=sys.stderr)
            return 1
        bundle[name] = json.loads(p.read_text())

    # Derived headline figures — computed, never hand-typed, so they cannot
    # drift away from the data they summarise.
    opps = bundle["opportunities"]["opportunities"]
    cov = {c["field"]: c for c in bundle["gaps"]["field_coverage"]}
    bundle["summary"] = {
        "opportunities": len(opps),
        "vendors": len(bundle["vendors"]["vendors"]),
        "tracks": {t["id"]: sum(1 for o in opps if o["track"] == t["id"])
                   for t in bundle["opportunities"]["tracks"]},
        "sector_count": len(bundle["sectors"]["sectors"]),
        "load_types": sum(len(s["loads"]) for s in bundle["sectors"]["sectors"]),
        "cited_rows": sum(1 for o in opps if o.get("sources")),
        "land_pct": cov["land_acres"]["pct"],
        "filing_pct": cov["utility_filing"]["pct"],
        "built": datetime.date.today().isoformat(),
    }

    SITE.mkdir(exist_ok=True)
    js = "/* generated by tools/build_data.py — do not edit */\nwindow.MR=" + \
         json.dumps(bundle, separators=(",", ":")) + ";\n"
    (SITE / "data.js").write_text(js)
    s = bundle["summary"]
    print(f"site/data.js  {len(js):,} bytes")
    print(f"  {s['opportunities']} opportunities ({s['cited_rows']} cited)  "
          f"{s['vendors']} vendors  {s['sector_count']} sectors / {s['load_types']} load types")
    print(f"  tracks: {s['tracks']}")
    return 0

if __name__ == "__main__":
    sys.exit(main())
